# Site settings
title: GSA Open Technology
description: Open source code, data and APIs from GSA.
baseurl: "/open-gsa" # the subpath of your site, e.g. /blog/
url: "https://github.com/GSA/open-gsa-redesign" # the base hostname & protocol for your site
logo: /assets/img/gsa-logo-dark.jpg
feature_image: /assets/img/feature-background.jpg

colors:
  background: '#ffffff'
  button:
    background: '#0071bc'
    hover: '#3e94cf'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  projects:
    accent: '#02bfe7'
  banner:
    background: '#fff'
    text: '#112e51'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    background: '#5b616b'
    text: '#fff'
analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: Digital Service # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - page
      - "project-list"
      - project

forms:
- type: newsletter
  heading: Sign up to receive updates from our team
  url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSdTKaMGI8PGKdR7VjuRRMtvOiA-uiD5fqqsFoyN1g2SXoLTqQ/formResponse
  button: Subscribe
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>
  fields:
    - type: email
      name: entry.474991268
      label: Email Address

- type: feedback
  heading: Any feedback?
  url: https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSdTKaMGI8PGKdR7VjuRRMtvOiA-uiD5fqqsFoyN1g2SXoLTqQ/viewform
  button: Submit
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>
  fields:
    - type: email
      name: entry.474991268
      label: Email Address
    - type: comments
      name: entry.474991268
      label: Comments

footer:
  image: /assets/img/logos/gsads-logo.svg
  image-alt: GSA Digital Service
  email:
  twitter:
    - USGSA
  text:  BUILT BY # Change to a tag line for your agency

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude: [node_modules, gulpifle.js, CONTRIBUTING.md, LICENSE.md, README.md]
