openapi: 3.0.0
info:
  title: Agency
  contact: {}
  version: '1.0'
servers:
- url: http://www.fpdsng.com/FPDS/BusinessServices/DataCollection/contracts/1.0/Agency
  variables: {}
paths:
  /getNewAgencyURL:
    post:
      tags:
      - AgencyBinding
      summary: getNewAgencyURL
      operationId: GetNewAgencyURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getNewAgencyURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNewAgencyURLOutput'
      deprecated: false
  /getExistingAgencyURL:
    post:
      tags:
      - AgencyBinding
      summary: getExistingAgencyURL
      operationId: GetExistingAgencyURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getExistingAgencyURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getExistingAgencyURLOutput'
      deprecated: false
components:
  schemas:
    getNewAgencyURLResponseType:
      title: getNewAgencyURLResponseType
      required:
      - agencyURL
      type: object
      properties:
        agencyURL:
          type: string
      description: ''
    getExistingAgencyURLResponseType:
      title: getExistingAgencyURLResponseType
      required:
      - agencyURL
      type: object
      properties:
        agencyURL:
          type: string
      description: ''
    getExistingAgencyURLInput:
      title: getExistingAgencyURLInput
      required:
      - authenticationKey
      - agencyID
      type: object
      properties:
        authenticationKey:
          type: string
        agencyID:
          type: string
    getExistingAgencyURLOutput:
      title: getExistingAgencyURLOutput
      required:
      - agencyURL
      type: object
      properties:
        agencyURL:
          $ref: '#/components/schemas/getExistingAgencyURLResponseType'
    getNewAgencyURLInput:
      title: getNewAgencyURLInput
      required:
      - authenticationKey
      - agency
      type: object
      properties:
        authenticationKey:
          type: string
        agency:
          type: string
    getNewAgencyURLOutput:
      title: getNewAgencyURLOutput
      required:
      - agencyURL
      type: object
      properties:
        agencyURL:
          $ref: '#/components/schemas/getNewAgencyURLResponseType'
tags:
- name: AgencyBinding
  description: ''
