openapi: 3.0.0
info:
  title: NAICS
  contact: {}
  version: '1.0'
servers:
- url: http://www.fpdsng.com/FPDS/BusinessServices/DataCollection/contracts/1.0/NAICS
  variables: {}
paths:
  /getNewNAICSURL:
    post:
      tags:
      - NAICSBinding
      summary: getNewNAICSURL
      operationId: GetNewNAICSURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getNewNAICSURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNewNAICSURLOutput'
      deprecated: false
  /getExistingNAICSURL:
    post:
      tags:
      - NAICSBinding
      summary: getExistingNAICSURL
      operationId: GetExistingNAICSURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getExistingNAICSURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getExistingNAICSURLOutput'
      deprecated: false
components:
  schemas:
    getNewNAICSURLResponseType:
      title: getNewNAICSURLResponseType
      required:
      - NAICSURL
      type: object
      properties:
        NAICSURL:
          type: string
      description: ''
    getExistingNAICSURLResponseType:
      title: getExistingNAICSURLResponseType
      required:
      - NAICSURL
      type: object
      properties:
        NAICSURL:
          type: string
      description: ''
    getExistingNAICSURLInput:
      title: getExistingNAICSURLInput
      required:
      - authenticationKey
      - NAICSCode
      type: object
      properties:
        authenticationKey:
          type: string
        NAICSCode:
          type: string
    getExistingNAICSURLOutput:
      title: getExistingNAICSURLOutput
      required:
      - NAICSURL
      type: object
      properties:
        NAICSURL:
          $ref: '#/components/schemas/getExistingNAICSURLResponseType'
    getNewNAICSURLInput:
      title: getNewNAICSURLInput
      required:
      - authenticationKey
      - NAICS
      type: object
      properties:
        authenticationKey:
          type: string
        NAICS:
          type: string
    getNewNAICSURLOutput:
      title: getNewNAICSURLOutput
      required:
      - NAICSURL
      type: object
      properties:
        NAICSURL:
          $ref: '#/components/schemas/getNewNAICSURLResponseType'
tags:
- name: NAICSBinding
  description: ''
