openapi: 3.0.0
info:
  title: PSC
  contact: {}
  version: '1.0'
servers:
- url: http://www.fpdsng.com/FPDS/BusinessServices/DataCollection/contracts/1.0/PSC
  variables: {}
paths:
  /getNewPSCURL:
    post:
      tags:
      - PSCBinding
      summary: getNewPSCURL
      operationId: GetNewPSCURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getNewPSCURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNewPSCURLOutput'
      deprecated: false
  /getExistingPSCURL:
    post:
      tags:
      - PSCBinding
      summary: getExistingPSCURL
      operationId: GetExistingPSCURL
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getExistingPSCURLInput'
        required: true
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getExistingPSCURLOutput'
      deprecated: false
components:
  schemas:
    getNewPSCURLResponseType:
      title: getNewPSCURLResponseType
      required:
      - PSCURL
      type: object
      properties:
        PSCURL:
          type: string
      description: ''
    getExistingPSCURLResponseType:
      title: getExistingPSCURLResponseType
      required:
      - PSCURL
      type: object
      properties:
        PSCURL:
          type: string
      description: ''
    getExistingPSCURLInput:
      title: getExistingPSCURLInput
      required:
      - authenticationKey
      - PSCCode
      type: object
      properties:
        authenticationKey:
          type: string
        PSCCode:
          type: string
    getExistingPSCURLOutput:
      title: getExistingPSCURLOutput
      required:
      - PSCURL
      type: object
      properties:
        PSCURL:
          $ref: '#/components/schemas/getExistingPSCURLResponseType'
    getNewPSCURLInput:
      title: getNewPSCURLInput
      required:
      - authenticationKey
      - PSC
      type: object
      properties:
        authenticationKey:
          type: string
        PSC:
          type: string
    getNewPSCURLOutput:
      title: getNewPSCURLOutput
      required:
      - PSCURL
      type: object
      properties:
        PSCURL:
          $ref: '#/components/schemas/getNewPSCURLResponseType'
tags:
- name: PSCBinding
  description: ''
